name: Compilation & tests

on:
  workflow_dispatch:
  push:
    branches:
    - master
    - develop
  pull_request:

jobs:

  build_application:
    name: Build application
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: compiled_app_binaries

  e2e_tests:
    name: Binance e2e tests
    strategy:
      matrix:
        device: ["nanos", "nanox", "nanosp", "stax"]
      fail-fast: false
    needs:
      - build_application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Build/Install build js deps
        run: cd tests_zemu && npm install

      - name: Download app binaries
        uses: actions/download-artifact@v3
        with:
          name: compiled_app_binaries
          path: build

      - name: Run zemu tests
        run: cd tests_zemu && npm run test -- -t "\(${{ matrix.device }}\)"

      - name: Upload snapshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.device }}-zemu-snapshots
          path: tests_zemu/snapshots-tmp/
